"""add is online coloum

Revision ID: 10e0adfe8fe5
Revises: ed0c3dae43a9
Create Date: 2017-05-10 17:33:03.476123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e0adfe8fe5'
down_revision = 'ed0c3dae43a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_online', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_online')
    # ### end Alembic commands ###
