"""add has_readed field

Revision ID: 14e8bf2f7ae6
Revises: 10e0adfe8fe5
Create Date: 2017-05-13 10:39:06.787199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e8bf2f7ae6'
down_revision = '10e0adfe8fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChatRecord', sa.Column('hasReaded', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ChatRecord', 'hasReaded')
    # ### end Alembic commands ###
